/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Solution */

#ifndef _Included_Solution
#define _Included_Solution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Solution
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Solution_intMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
